name: Check README on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Check for README changes
        id: check_diff
        run: |
          git add README.md
          if ! git diff --cached --quiet; then
            echo "README would be updated by this PR."
            # Print warning annotation for GitHub UI (yellow warning)
            echo "::warning file=README.md::README would be updated by this PR. Please update README."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "README is up to date."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # Optional: add a step to show the warning result in the workflow summary
      - name: Warn if README out of date
        if: steps.check_diff.outputs.changed == 'true'
        run: echo "⚠️ README would be updated by this PR. Once the branch is merged to main, a new PR will be opened with an updated README."
