name: Check README on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Check for README changes
        run: |
          git add README.md
          if ! git diff --cached --quiet; then
            echo "README would be updated by this PR. Please update README."
            exit 1   # fail the job, so the PR shows a failing check
          else
            echo "README is up to date."
          fi
