name: Generate README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install requests

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Commit and push README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-generate README.md'
          file_pattern: 'README.md'
