name: Generate README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install requests

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Configure git user
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"

      - name: Commit README changes if any
        id: commit
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: auto-generate README.md"
            echo "push=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Push changes with PAT
        if: steps.commit.outputs.push == 'true'
        env:
           PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
           echo "Pushing changes to branch ${{ github.ref_name }}"
           git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
