name: Update README on main

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # ensures a local main branch exists

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"

      - name: Commit changes if any
        run: |
          git add README.md
          if git diff-index --quiet HEAD --; then
            echo "No changes."
          else
            git commit -m "chore: auto-update README"
            git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
            git push origin main
          fi
