name: Generate README and Update Meta Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Configure git user
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"

      - name: Commit changes if any
        id: commit
        run: |
          git add README.md pyladies_meta_data.pkl || true
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: auto-update README and meta data"
            echo "push=true" >> $GITHUB_OUTPUT
          fi

      - name: Determine branch to push
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Push changes with PAT
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          branch: ${{ steps.vars.outputs.branch }}
