name: Generate README and Update Meta Data

on:
  pull_request:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Configure git user
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"

      - name: Commit changes if any
        id: commit
        run: |
          git add README.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: auto-update README"
            echo "push=true" >> $GITHUB_OUTPUT
          fi

      - name: Determine branch to push
        id: vars
        run: |
          echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

      - name: Push changes with PAT
        if: steps.commit.outputs.push == 'true' && steps.check_branch.outputs.push_allowed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
           github_token: ${{ secrets.ACTIONS_PAT }}
           branch: ${{ github.head_ref }}
