name: Check README Generation

on:
  pull_request:
    branches: [main]

jobs:
  test-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run README generator
        run: python scripts/generate_readme.py

      - name: Show diff if any
        run: |
          git diff --exit-code || echo "README would be updated."
