name: Trigger README update on PR

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
        
permissions:
  contents: read
  pull-requests: write

jobs:
  call-update-readme:
    uses: ./.github/workflows/update_readme.yml
    with:
      head_ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
